// <auto-generated />
using System;
using BudgetBackend.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetBackend.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20250907090648_CreateDBAndTable")]
    partial class CreateDBAndTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetBackend.Models.Entities.TaxPlanForFinancialYearEntity", b =>
                {
                    b.Property<Guid>("TaxPlanForFinancialYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TaxPlanForFinancialYearID");

                    b.Property<string>("FinancialYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FinancialYear");

                    b.Property<string>("InvestingIn")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InvestingIn");

                    b.Property<int>("InvestmentAmount")
                        .HasColumnType("int")
                        .HasColumnName("InvestmentAmount");

                    b.Property<string>("InvestmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("InvestmentName");

                    b.Property<int>("NoOfMonths")
                        .HasColumnType("int")
                        .HasColumnName("NoOfMonths");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Section");

                    b.HasKey("TaxPlanForFinancialYearId");

                    b.ToTable("TaxPlanForFinancialYear");
                });

            modelBuilder.Entity("BudgetBackend.Models.Entities.TaxPlanTransactionsEntity", b =>
                {
                    b.Property<Guid>("TaxPlanTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TaxPlanTransactionID");

                    b.Property<Guid>("TaxPlanForFinancialYearId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TaxPlanForFinancialYearID");

                    b.Property<int>("TransactionAmount")
                        .HasColumnType("int")
                        .HasColumnName("TransactionAmount");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TransactionDate");

                    b.HasKey("TaxPlanTransactionId");

                    b.ToTable("TaxPlanTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
